# Pre-commit hooks for MLOps Platform
# See https://pre-commit.com for more information

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.venv/
      - id: end-of-file-fixer
        exclude: ^\.venv/
      - id: check-yaml
        exclude: ^architecture/structurizr/workspace\.dsl$
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=10000  # 10MB limit
      - id: mixed-line-ending
        args:
          - --fix=lf

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11
        args:
          - --line-length=88
        exclude: ^\.venv/

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=88
        exclude: ^\.venv/

  # Basic linting (very permissive to start)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --extend-ignore=E203,W503,E501,F401,F841,F811,F541,E722,E712,E101,E266,E265,W191
          - --max-complexity=30
          - --exclude=.venv,.git,__pycache__,build,dist,*.egg-info,notebooks

  # Jupyter notebook cleaning (basic)
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      - id: nbqa-black
        args:
          - --line-length=88

# Global exclusions
exclude: |
  (?x)^(
    \.venv/.*|
    \.git/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    .*\.egg-info/.*|
    app_data/.*|
    data/.*|
    models/.*|
    logs/.*|
    reports/.*|
    artifacts/.*|
    mlruns/.*|
    \.env.*|
    bandit-report\.json|
    safety-report\.json
  )$

# Configuration
default_stages: [pre-commit]
fail_fast: false
minimum_pre_commit_version: 3.0.0
