name: mlops-zoomcamp-project
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: mlops-postgres
    environment:
      POSTGRES_DB: mlops
      POSTGRES_USER: mlops_user
      POSTGRES_PASSWORD: mlops_password
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./app_data/postgres:/var/lib/postgresql/data
    networks:
      - mlops-network

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: mlops-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - mlops-network

  # MLFlow Tracking Server
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    container_name: mlops-mlflow
    ports:
      - "${MLFLOW_PORT:-5000}:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=${DATABASE_URL}
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://mlflow-artifacts/
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - AWS_DEFAULT_REGION=us-east-1
    command: >
      /bin/sh -c "pip install psycopg2-binary boto3 && mlflow server
      --backend-store-uri ${DATABASE_URL}
      --default-artifact-root s3://mlflow-artifacts/
      --host 0.0.0.0
      --port 5000"
    depends_on:
      - postgres
      - localstack
    networks:
      - mlops-network

  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: mlops-prefect-server
    ports:
      - "${PREFECT_PORT:-4200}:${PREFECT_PORT:-4200}"
    environment:
      - PREFECT_UI_URL=http://localhost:${PREFECT_PORT:-4200}
      - PREFECT_API_URL=http://localhost:${PREFECT_PORT:-4200}/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    command: prefect server start --host 0.0.0.0 --port ${PREFECT_PORT:-4200}
    volumes:
      - prefect_data:/root/.prefect
    networks:
      - mlops-network

  # LocalStack for AWS services emulation
  localstack:
    image: localstack/localstack:latest
    container_name: mlops-localstack
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
      - "${LOCALSTACK_PORT_RANGE_START:-4510}-${LOCALSTACK_PORT_RANGE_END:-4559}:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=s3,secretsmanager,ssm,cloudformation,iam,lambda
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./app_data/localstack:/tmp
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mlops-network

  # Initialize LocalStack S3 buckets
  localstack-setup:
    image: amazon/aws-cli:latest
    container_name: mlops-localstack-setup
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ENDPOINT_URL=http://localstack:${LOCALSTACK_PORT:-4566}
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for LocalStack to be ready...';
      while ! aws --endpoint-url=http://localstack:${LOCALSTACK_PORT:-4566} s3 ls > /dev/null 2>&1; do
        sleep 2;
      done;
      echo 'Creating S3 buckets...';
      aws --endpoint-url=http://localstack:${LOCALSTACK_PORT:-4566} s3 mb s3://mlflow-artifacts || true;
      aws --endpoint-url=http://localstack:${LOCALSTACK_PORT:-4566} s3 mb s3://data-lake || true;
      aws --endpoint-url=http://localstack:${LOCALSTACK_PORT:-4566} s3 mb s3://model-artifacts || true;
      echo 'S3 buckets created successfully';
      exit 0;
      "
    networks:
      - mlops-network

  # Initialize Prefect work pool and start worker
  prefect-setup:
    image: prefecthq/prefect:3-latest
    container_name: mlops-prefect-setup
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://mlops-prefect-server:${PREFECT_PORT:-4200}/api
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for Prefect server to be ready...';
      sleep 15;
      echo 'Creating default work pool...';
      prefect work-pool create default-agent-pool --type process || echo 'Work pool already exists';
      echo 'Starting Prefect worker...';
      prefect worker start --pool default-agent-pool;
      "
    networks:
      - mlops-network

volumes:
  redis_data:
  prefect_data:
  localstack_data:

networks:
  mlops-network:
    driver: bridge
