services:
  structurizr:
    image: structurizr/lite:latest
    container_name: structurizr-lite
    ports:
      - "${STRUCTURIZR_PORT:-8080}:8080"
    volumes:
      - ./structurizr/workspace.dsl:/usr/local/structurizr/workspace.dsl:ro
#    environment:
#      - STRUCTURIZR_WORKSPACE_FILENAME=workspace.dsl
    restart: unless-stopped
    
  # PlantUML server for diagram rendering (optional)
  plantuml:
    image: plantuml/plantuml-server:latest
    container_name: plantuml-server
    ports:
      - "${PLANTUML_PORT:-8081}:8080"
    restart: unless-stopped
