# Data configuration
first_snapshot_month: "2017-05" # Month to generate first data snapshot

data_path:
  # Local filesystem paths (for direct execution)
  local_paths:
    raw: "data/raw"
    processed: "data/processed"
    feature: "data/features"

# MLFlow configuration
mlflow:
  tracking_uri: "http://localhost:5005"
  artifact_location: "mlruns"
  s3_endpoint_url: "http://localhost:9000"
  s3_access_key: "minioadmin"
  s3_secret_key: "minioadmin"

# Prefect configuration
prefect:
  api_url: "http://localhost:4200/api"
  work_pool: "default-agent-pool"

# Environment settings
environment: "development"
debug: true
log_level: "INFO"

# Infrastructure
database_url: "postgresql://localhost:5432/mlops"
redis_url: "redis://localhost:6379"

# Storage configuration
storage:
  endpoint_url: "http://mlops-minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  region: "us-east-1"
  buckets:
    mlflow_artifacts: "mlflow-artifacts"
    data_lake: "data-lake"
    model_artifacts: "model-artifacts"
  # S3/MinIO paths within buckets (for containerized execution)
  s3_paths:
    raw: "data/raw"
    processed: "data/processed"
    features: "data/features"
    models: "models"
    experiments: "experiments"
    prefect_flows: "prefect-flows"
